--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4 (Debian 17.4-1.pgdg120+2)
-- Dumped by pg_dump version 17.0

-- Started on 2025-06-03 15:40:00

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA public;


--
-- TOC entry 3414 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 222 (class 1259 OID 50263)
-- Name: exercicio_gramatica_complementar; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.exercicio_gramatica_complementar (
    id integer NOT NULL,
    frase_completa character varying(255),
    frase_incompleta character varying(255),
    id_ordem_exercicio integer,
    id_plano_estudo integer,
    opcao_correta character varying(255),
    opcao_incorreta character varying(255)[]
);


--
-- TOC entry 221 (class 1259 OID 50262)
-- Name: exercicio_gramatica_complementar_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.exercicio_gramatica_complementar ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exercicio_gramatica_complementar_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 50271)
-- Name: exercicio_gramatica_ordem; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.exercicio_gramatica_ordem (
    id integer NOT NULL,
    frase_completa character varying(255),
    id_ordem_exercicio integer,
    id_plano_estudo integer,
    ordem_aleatoria character varying(255)[],
    ordem_correta character varying(255)[]
);


--
-- TOC entry 223 (class 1259 OID 50270)
-- Name: exercicio_gramatica_ordem_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.exercicio_gramatica_ordem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exercicio_gramatica_ordem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 50279)
-- Name: exercicio_vocabulario_pares; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.exercicio_vocabulario_pares (
    id integer NOT NULL,
    id_ordem_exercicio integer,
    id_plano_estudo integer,
    pares_direita character varying(255)[],
    pares_esquerda character varying(255)[]
);


--
-- TOC entry 225 (class 1259 OID 50278)
-- Name: exercicio_vocabulario_pares_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.exercicio_vocabulario_pares ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exercicio_vocabulario_pares_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 50287)
-- Name: plano_estudo; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.plano_estudo (
    id integer NOT NULL,
    id_preferencia integer,
    id_usuario integer,
    qt_exercicios_dia integer,
    tipos_exercicios_contidos smallint[],
    ativo boolean,
    data date
);


--
-- TOC entry 227 (class 1259 OID 50286)
-- Name: plano_estudo_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.plano_estudo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.plano_estudo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 42072)
-- Name: preferencias; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.preferencias (
    id integer NOT NULL,
    ativo boolean,
    data_criacao timestamp(6) without time zone,
    dia_semana smallint[],
    dificuldade character varying(255),
    id_usuario integer,
    idioma character varying(255),
    nivel character varying(255),
    temas character varying(255)[],
    tempo_minutos integer,
    tipo_exercicio character varying(255)[]
);


--
-- TOC entry 217 (class 1259 OID 42071)
-- Name: preferencias_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.preferencias ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.preferencias_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 42080)
-- Name: usuario; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuario (
    id integer NOT NULL,
    email character varying(255),
    nome_completo character varying(255),
    password character varying(255),
    plano smallint,
    username character varying(255),
    CONSTRAINT usuario_plano_check CHECK (((plano >= 0) AND (plano <= 3)))
);


--
-- TOC entry 219 (class 1259 OID 42079)
-- Name: usuario_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.usuario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3402 (class 0 OID 50263)
-- Dependencies: 222
-- Data for Name: exercicio_gramatica_complementar; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.exercicio_gramatica_complementar VALUES (1, 'SpongeBob lives in a pineapple under the sea.', 'SpongeBob lives in a ... under the sea.', 0, 3, 'pineapple', '{castle,ship,stone}');
INSERT INTO public.exercicio_gramatica_complementar VALUES (2, 'Patrick is SpongeBob''s best friend.', 'Patrick is SpongeBob''s best ...', 1, 3, 'friend', '{neighbor,enemy,teacher}');
INSERT INTO public.exercicio_gramatica_complementar VALUES (3, 'Jellyfish float gracefully through the ocean.', 'Jellyfish ... gracefully through the ocean.', 2, 3, 'float', '{run,jump,walk}');


--
-- TOC entry 3404 (class 0 OID 50271)
-- Dependencies: 224
-- Data for Name: exercicio_gramatica_ordem; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.exercicio_gramatica_ordem VALUES (1, 'Sandy wears a suit to live underwater.', 3, 3, '{underwater.,Sandy,suit,a,live,wears,to}', '{Sandy,wears,a,suit,to,live,underwater.}');
INSERT INTO public.exercicio_gramatica_ordem VALUES (2, 'The Krusty Krab is a famous burger restaurant.', 4, 3, '{famous,burger,restaurant.,Krusty,is,a,Krab,The}', '{The,Krusty,Krab,is,a,famous,burger,restaurant.}');
INSERT INTO public.exercicio_gramatica_ordem VALUES (3, 'Squidward plays the clarinet every afternoon.', 5, 3, '{the,afternoon.,Squidward,clarinet,plays,every}', '{Squidward,plays,the,clarinet,every,afternoon.}');


--
-- TOC entry 3406 (class 0 OID 50279)
-- Dependencies: 226
-- Data for Name: exercicio_vocabulario_pares; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.exercicio_vocabulario_pares VALUES (1, 6, 3, '{esponja,amigo,oceano,abacaxi}', '{sponge,friend,ocean,pineapple}');
INSERT INTO public.exercicio_vocabulario_pares VALUES (2, 7, 3, '{caranguejo,clarinete,água-viva,restaurante}', '{crab,clarinet,jellyfish,restaurant}');
INSERT INTO public.exercicio_vocabulario_pares VALUES (3, 8, 3, '{"debaixo d''água",flutuar,traje,mar}', '{underwater,float,suit,sea}');


--
-- TOC entry 3408 (class 0 OID 50287)
-- Dependencies: 228
-- Data for Name: plano_estudo; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.plano_estudo VALUES (2, 1, 1, NULL, NULL, NULL, '2025-06-03');
INSERT INTO public.plano_estudo VALUES (1, 1, 2, NULL, NULL, true, '2025-06-03');
INSERT INTO public.plano_estudo VALUES (3, 1, 1, NULL, NULL, false, '2025-06-03');


--
-- TOC entry 3398 (class 0 OID 42072)
-- Dependencies: 218
-- Data for Name: preferencias; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.preferencias VALUES (1, true, '2025-05-30 11:26:10.669', '{0}', 'media', 1, 'ingles', 'media', '{"bob esponja",desenhos,"fundo do mar"}', 45, '{teste}');


--
-- TOC entry 3400 (class 0 OID 42080)
-- Dependencies: 220
-- Data for Name: usuario; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.usuario VALUES (1, 'teste', 'string teste', '$2a$10$n1L9fZABsjVMKokEu/NfsO.hAakWV5QlXPNcCwrj9n4nhknRQBM/C', 0, 'teste');


--
-- TOC entry 3415 (class 0 OID 0)
-- Dependencies: 221
-- Name: exercicio_gramatica_complementar_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.exercicio_gramatica_complementar_id_seq', 3, true);


--
-- TOC entry 3416 (class 0 OID 0)
-- Dependencies: 223
-- Name: exercicio_gramatica_ordem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.exercicio_gramatica_ordem_id_seq', 3, true);


--
-- TOC entry 3417 (class 0 OID 0)
-- Dependencies: 225
-- Name: exercicio_vocabulario_pares_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.exercicio_vocabulario_pares_id_seq', 3, true);


--
-- TOC entry 3418 (class 0 OID 0)
-- Dependencies: 227
-- Name: plano_estudo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.plano_estudo_id_seq', 3, true);


--
-- TOC entry 3419 (class 0 OID 0)
-- Dependencies: 217
-- Name: preferencias_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.preferencias_id_seq', 1, true);


--
-- TOC entry 3420 (class 0 OID 0)
-- Dependencies: 219
-- Name: usuario_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.usuario_id_seq', 1, true);


--
-- TOC entry 3245 (class 2606 OID 50269)
-- Name: exercicio_gramatica_complementar exercicio_gramatica_complementar_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exercicio_gramatica_complementar
    ADD CONSTRAINT exercicio_gramatica_complementar_pkey PRIMARY KEY (id);


--
-- TOC entry 3247 (class 2606 OID 50277)
-- Name: exercicio_gramatica_ordem exercicio_gramatica_ordem_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exercicio_gramatica_ordem
    ADD CONSTRAINT exercicio_gramatica_ordem_pkey PRIMARY KEY (id);


--
-- TOC entry 3249 (class 2606 OID 50285)
-- Name: exercicio_vocabulario_pares exercicio_vocabulario_pares_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exercicio_vocabulario_pares
    ADD CONSTRAINT exercicio_vocabulario_pares_pkey PRIMARY KEY (id);


--
-- TOC entry 3251 (class 2606 OID 50293)
-- Name: plano_estudo plano_estudo_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plano_estudo
    ADD CONSTRAINT plano_estudo_pkey PRIMARY KEY (id);


--
-- TOC entry 3237 (class 2606 OID 42078)
-- Name: preferencias preferencias_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.preferencias
    ADD CONSTRAINT preferencias_pkey PRIMARY KEY (id);


--
-- TOC entry 3239 (class 2606 OID 42089)
-- Name: usuario uk5171l57faosmj8myawaucatdw; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT uk5171l57faosmj8myawaucatdw UNIQUE (email);


--
-- TOC entry 3241 (class 2606 OID 42091)
-- Name: usuario uk863n1y3x0jalatoir4325ehal; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT uk863n1y3x0jalatoir4325ehal UNIQUE (username);


--
-- TOC entry 3243 (class 2606 OID 42087)
-- Name: usuario usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_pkey PRIMARY KEY (id);


-- Completed on 2025-06-03 15:40:00

--
-- PostgreSQL database dump complete
--

